name: Clear cache

on:
  schedule:
    - cron: "20-30 * * * *"
  workflow_dispatch:
    inputs:
      clear-older-than-days:
        description: "Older than days"
        type: number
        default: 2
      size-threshold:
        description: "Size threshold in MB"
        type: number
        default: 9216

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            const usage = await github.rest.actions.getActionsCacheUsage({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(
              "current cache usage is: %f MB",
              (usage.data.active_caches_size_in_bytes / 1024.0 / 1024.0).toFixed(2)
            )
            if (usage.data.active_caches_size_in_bytes < ${{ inputs.size-threshold || 9216 }} * 1024 * 1024 ) {
              console.log("size is too small, exiting")
              return
            }
            
            const clearOlderThanDays = ${{ inputs.clear-older-than-days || 2 }}
            var dateThreshold = new Date()
            dateThreshold.setDate(dateThreshold.getDate() - clearOlderThanDays)
            console.log("threshold:", dateThreshold)

            console.log("get list of caches for repository.")
            const opts = github.rest.actions.getActionsCacheList.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              sort: "last_accessed_at",
              direction: "asc",
            })
            const caches = await github.paginate(opts)

            for (const cache of caches) {
              const lastAccessedAt = new Date(Date.parse(cache.last_accessed_at))
              if (lastAccessedAt > dateThreshold) {
                break
              }

              console.log("clear cache", cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
