name: Clear cache

on:
  schedule:
    - cron: "* * * * *"

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            const sizeThreshold = 9216 * 1024 * 1024
            const clearOlderThanDays = 2
            
            const usage = await github.rest.actions.getActionsCacheUsage({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(
              "current cache usage is: %f MB",
              (usage.data.active_caches_size_in_bytes / 1024.0 / 1024.0).toFixed(2)
            )
            if (usage.data.active_caches_size_in_bytes < sizeThreshold ) {
              console.log("size is too small, exiting")
              return
            }
            
            var dateThreshold = new Date()
            dateThreshold.setDate(dateThreshold.getDate() - clearOlderThanDays)
            console.log("threshold:", dateThreshold)

            console.log("get list of caches for repository.")
            const opts = github.rest.actions.getActionsCacheList.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              sort: "last_accessed_at",
              direction: "asc",
            })
            const caches = await github.paginate(opts)

            for (const cache of caches) {
              const lastAccessedAt = new Date(Date.parse(cache.last_accessed_at))
              if (lastAccessedAt > dateThreshold) {
                break
              }

              console.log("clear cache", cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
