name: Clear cache

on:
  workflow_dispatch:
    inputs:
      clear-older-than-days:
        description: "Older than days"
        type: number
        default: 2

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            const clearOlderThanDays = ${{ inputs.clear-older-than-days }}
            var dateThreshold = new Date()
            dateThreshold.setDate(dateThreshold.getDate() - clearOlderThanDays)
            console.log("threshold:", dateThreshold)

            console.log("get list of caches for repository.")
            const opts = github.rest.actions.getActionsCacheList.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              sort: "last_accessed_at",
              direction: "asc",
            })
            const caches = await github.paginate(opts)
            console.log(caches);

            for (const cache of caches) {
              const lastAccessedAt = new Date(Date.parse(cache.last_accessed_at))
              if (lastAccessedAt > dateThreshold) {
                break
              }

              console.log("clear cache", cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
